### ISSUE TITLE
HistoryAPI not working 

### ISSUE THREAD

**Issue by vijaychavan007** [paramatrixtech/ksapi#1]
1.
client.history("historicalprices",{"exchange":"bse","cocode":"476","fromdate":"01-jan-2014","todate":"08-oct-2015"})
Returns:
ApiException: (404)
Reason: Not Found
HTTP response body: <am:fault xmlns:am="http://wso2.org/apimanager"><am:code>404</am:code><am:type>Status report</am:type><am:message>Not Found</am:message><am:description>The requested resource is not available.</am:description></am:fault>

2.
client.history("NSEFNO_HistoricalContinuousChart",{"symbol":"HDFC","expiry type": "near"})
Returns:
ApiException: (404)
Reason: Not Found
HTTP response body: <am:fault xmlns:am="http://wso2.org/apimanager"><am:code>404</am:code><am:type>Status report</am:type><am:message>Not Found</am:message><am:description>The requested resource is not available.</am:description></am:fault>

**Comment by dhwajsinghal** [comment]
Hi, we dont currently provide historical data APIs.

**Comment by mpunekar** [comment]
Hello, any plan to start historical data APIs soon?

**Comment by Sid1249** [comment]
@dhwajsinghal 
Here it says you do provide Historical Data?
<img width="348" alt="Screenshot 2023-01-27 at 10 44 55 AM" src="https://user-images.githubusercontent.com/33166377/215014623-07bc1545-58d3-4246-b775-824ce86d448c.png">
