### ISSUE TITLE
order_report API is throwing error

### ISSUE THREAD

**Issue by AddsK** [paramatrixtech/ksapi#11]
When I try to see my orders and used order_report API and getting error "OTIM MODULE NOT AVAILABLE".
**Error message**:
Exception has occurred: ApiException
(424)
Reason: Failed Dependency
HTTP response body: {"fault":{"code":999321,"description":"-","message":"OTIM MODULE NOT AVAILABLE"}}

My second question is, does this response contains order id?

**Comment by dhwajsinghal** [comment]
to answer your second question, yes. the order report contains order IDs

**Comment by AddsK** [comment]
> Hi @AddsK please try again now. Also what time were you trying to call this API request? If it was late at night, it may have been due to the fact that we run certain EOD processes around that time which causes servers to be temporarily unavailable

Thank you for the reply! This would be great if we get reply in 24 hours.
Yes order report is working now.

**Comment by AddsK** [comment]
> to answer your second question, yes. the order report contains order IDs

Thank you
