### ISSUE TITLE
Unsubscribe one or multiple tokens without stopping streaming service

### ISSUE THREAD

**Issue by AddsK** [paramatrixtech/ksapi#13]
Hi,

I want to unsubscribe specific token(s) which I subscribed already in streaming/websocket service.
Ex:- I subscribed for HDFC Bank, ICICI Bank, Kotak Bank and later some point I want to unsubscribe only ICICI Bank ( I don't need price streaming), how can I do that?
Please explain with some examples.

Thank you!

**Comment by tiwaribasu** [comment]
You can make the token read from local file list & make changes in it to make it active/inactive accordingly.

**Comment by dhwajsinghal** [comment]
alternatively you can also use threading to unload a token without halting the websocket function by running them in individual threads.
