### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by mithunpradeep** [paramatrixtech/ksapi#14]
I am getting following error while trying to login through API.

{"fault":{"code":900901,"message":"Invalid Credentials","description":"Access failure for API: /apim/session/1.0, version: 1.0 status: (900901) - Invalid Credentials. Make sure you have provided the correct security credentials"}}

**Comment by altimetrikchallenge** [comment]
Same issue for me.

**Comment by dhwajsinghal** [comment]
Please try using "https://tradeapi.kotaksecurities.com/apim" and "https://ctradeapi.kotaksecurities.com/apim" both as hosts for your init function. 

If neither of them works, Then please send an email to ks.apihelp@kotak.com stating invalid credentials as your error message, along with your User ID or Client Code
