### ISSUE TITLE
i am not able to login:

### ISSUE THREAD

**Issue by vinayakbhovi** [paramatrixtech/ksapi#16]
i am not able to login:

from ks_api_client import ks_api
# Defining the host is optional and defaults to https://sbx.kotaksecurities.com/apim
# See configuration.py for a list of all supported configuration parameters.
client = ks_api.KSTradeApi(access_token = "", userid = "", consumer_key = "",ip = "127.0.0.1", app_id = "test", \
                        host = "https://tradeapi.kotaksecurities.com/apim", consumer_secret = "")
					 
# Initiate login and generate OTT
client.login(password = "")

#Complete login and generate session token
client.session_2fa()

it is giving me the following error

TypeError: __init__() got an unexpected keyword argument 'consumer_secret'

**Comment by dhwajsinghal** [comment]
this may be due to an older version of the sdk. try updating the library on your device and running it again.

**Comment by dhwajsinghal** [comment]
Closing this issue. The consumer_Secret error you received is due to an older version of the sdk
