### ISSUE TITLE
Error order placement in Derivatives (i.e NIFTY,BANKNIFTY) 

### ISSUE THREAD

**Issue by ROSHAN0013** [paramatrixtech/ksapi#21]
hello @paramatrixtech ,
          Order placement with stocks is just fine. But it's not working with derivatives (i.e NIFTY, BANKNIFTY). 
Output error code is 1000 attached screenshot.
please resolve 

![Screenshot (16)](https://user-images.githubusercontent.com/103929818/163788211-837519f4-18f3-4fc5-9796-ce211d73971b.png)

**Comment by tiwaribasu** [comment]
OPTION Pricing should be in allowed range. Else, the ERROR pops up!!

**Comment by dhwajsinghal** [comment]
this error shows up when the price you send via the api request is beyond the allowed range (as specified in the error message)
