### ISSUE TITLE
#question

### ISSUE THREAD

**Issue by mehboob-dev** [paramatrixtech/ksapi#22]
How many token i can connect at a time via websocket. ?

How many websocket i can connect on 1 API ?

**Comment by mehboob-dev** [comment]
@dhwajsinghal @paramatrixtec

**Comment by dhwajsinghal** [comment]
you can connect to 30 tokens and 5 connections at a time

**Comment by mehboob-dev** [comment]
This means total 150 tokens i can connect ? 

Or in total with 5 connection only 30 tokens ?

Please specify

**Comment by dhwajsinghal** [comment]
150 tokens can be connected to
