### ISSUE TITLE
Error while closing orders

### ISSUE THREAD

**Issue by Avi0615** [paramatrixtech/ksapi#23]
![Error FIL 2](https://user-images.githubusercontent.com/104343680/165032847-deef0134-4664-4403-a338-b709b41f7b23.png)

Hi

I use Kotak Api to trade in bank nifty options. 

i have encountered one error while closing the open order. The system i have coded is if an order is placed at a particular time (let's say 09:16) must be traded off at a particular time(let's say 09:45). 

I had inserted one condition which checks at 09:45 if the order is traded or not and if not then it modifies the order to trade at 09:45. 

In between, if i believe the market will not be in my favor, I modify the order myself manually before the coded time (09:45 in this example). 

Doing this terminates my program at 09:45 giving the error message as **"ks_api_client.exceptions.Api exception: (999113) Order modification not allowed as current order status is FIL, ")**{screenshot attached} and thereafter terminating the program for future trades.

please help on why this error occur and how to rectify it

Thanks

**Comment by dhwajsinghal** [comment]
FIL implies that the order was traded. thats why your modification request wasnt going through

**Comment by Avi0615** [comment]
How should I insert the condition (via if loop) for capturing this order
status in my algo as the same terminates when this modification is not
possible.
