### ISSUE TITLE
Pls help how to get inst token of FNO

### ISSUE THREAD

**Issue by jayaprakashv2005** [paramatrixtech/ksapi#3]
Hi All,

Can someone Pls help how to get instrument token of FNO symbols like NIFTY CE/PE,
I could find for cash segment - https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_Cash_14_07_2021.txt, but not for FNO.
I feel there is no enough documentation.

thanks,

**Comment by AddsK** [comment]
Hi Jayaprkash,

Just replace Cash with FNO. Let me know if you are looking for something else

**Comment by ashwinkp** [comment]
Check https://github.com/osparamatrix/ks-orderapi-python/issues/77#issuecomment-1027885778

**Comment by dhwajsinghal** [comment]
Instrument tokens can be found at the following urls (NOTE: Please replace DD_MM_YYYY with the latest date for updated instrument tokens, for example 27_05_2021 will give tokens for 27 may):

Equity: https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_Cash_DD_MM_YYYY.txt

Derivatives: https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_DD_MM_YYYY.txt
