### ISSUE TITLE
Subscription to websocket seems to be broken.

### ISSUE THREAD

**Issue by jayaprakashv2005** [paramatrixtech/ksapi#4]
i followed the example, but I am getting AttributeError: 'KSTradeApi' object has no attribute 'subscribe'
pls help!

**Comment by PhoenixNK** [comment]
I was also getting same error, when I updated the API using the link given on the documentation, it worked for me.

**Comment by jayaprakashv2005** [comment]
Admins, pls let us know any alternative way to get ltps of multiple instruments in a single go.

**Comment by dhwajsinghal** [comment]
@jayaprakashv2005 
for websocket, please update to the latest version of the repository and let me know if the issue persists. 
for quotes. you can pass multiple instrument tokens by passing them as a string separated by a hyphen. 
for example, if you want quotes for token 727 and 1250 you will write: 
client.quote(instrument_token="727-1250")
