### ISSUE TITLE
Where are the Websocket details?

### ISSUE THREAD

**Issue by AddsK** [paramatrixtech/ksapi#5]
I'm looking for Websocket details. how to subscribe & how to connect.
Please provide the examples of websocket if possible

**Comment by PhoenixNK** [comment]
I am also looking for the Websocket sample code. Also contacted the team over email, but did not get the sample code.
Please provide sample code for websocket.

**Comment by sanket-parte** [comment]
Hi, you can find the websocket documentation below:
https://github.com/paramatrixtech/ksapi/blob/2270822b71583ed39f776ce9b1bc29383f02967d/python/docs/StreamingApi.md
