### ISSUE TITLE
Websocket sample code

### ISSUE THREAD

**Issue by PhoenixNK** [paramatrixtech/ksapi#6]
Please provide a sample code in Python for websocket connection, subscribing symbols and getting the ticks.

**Comment by sanket-parte** [comment]
Hi, you can find the websocket documentation below:
https://github.com/paramatrixtech/ksapi/blob/2270822b71583ed39f776ce9b1bc29383f02967d/python/docs/StreamingApi.md

**Comment by PhoenixNK** [comment]
Thanks for the link.
