### ISSUE TITLE
Websocket coninuously disconnecting

### ISSUE THREAD

**Issue by PhoenixNK** [paramatrixtech/ksapi#7]
Hi,
I succeeded to connect to the live streaming. But it is disconnecting frequently. Please see below the messages I received from streaming:

['0154101', '35397', '188.2000', '100', '188.5000', '50', '188.1500', '255.0000', '167.7000', '190.5200', '409.6500', '210.0000', '-54.0705', '425150', '471950', '22552000', '2369550', '4296607040.00', '50', '14/02/2022 10:24:01', '-221.5000', '1070.5500', '0.0500']
Your logic/computation will come here.
Connection closed
..........
...........
INFO:socketio.client:Engine.IO connection established.

Also, one major problem in the received messages is there is a list of values only. How do I know which value refers to what.
I mean how one would know out of the values which is ltp, which is volume and so on.

Could you please provide the response format?

**Comment by AddsK** [comment]
> Hi, I succeeded to connect to the live streaming. But it is disconnecting frequently. Please see below the messages I received from streaming:
> 
> ['0154101', '35397', '188.2000', '100', '188.5000', '50', '188.1500', '255.0000', '167.7000', '190.5200', '409.6500', '210.0000', '-54.0705', '425150', '471950', '22552000', '2369550', '4296607040.00', '50', '14/02/2022 10:24:01', '-221.5000', '1070.5500', '0.0500'] Your logic/computation will come here. Connection closed .......... ........... INFO:socketio.client:Engine.IO connection established.
> 
> Also, one major problem in the received messages is there is a list of values only. How do I know which value refers to what. I mean how one would know out of the values which is ltp, which is volume and so on.
> 
> Could you please provide the response format?

Hi PheonixNK,

I'm not getting the streaming data, can you please share how did you connect and what exactly in the computation method.

Really appreciate your help!

Thanks
Adds

**Comment by dhwajsinghal** [comment]
you can view the output structure [here](https://github.com/paramatrixtech/ksapi/blob/main/python/docs/StreamingApi.md#subscribe)
